# https://taskfile.dev
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  deploy: 
    desc: Deploys the containers to AWS EC Registry and GCP Artifact Registry
    cmds:
      - echo "Deploying application..."
      - # Add deployment commands here
  
